on:
  push:
    branches:
      - "main" 

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    
    - name: install deps
      run: npm install
      
    - name: build deps
      run: npm run deploy
